### ISSUE TITLE
А зачем мы bin в гите храним? 

### ISSUE THREAD

**Issue by splincode** [Angular-RU/ngx-i18n-combine#1]
Если он все равно указывает на dist в последствии, почему нельзя компилить сразу исходники с бинами?

https://github.com/Angular-RU/ngx-i18n-combine/blob/62112ff34e3650b913e1d710e162297d993f0741/bin/cli.js#L3

**Comment by AlexDaSoul** [comment]
Это не бины, это нужно для работы cli. dist - это обычные js-файлы. Не вижу смысла их компилить и складывать в гит. Все равно, что сложить сюда node_modules

**Comment by splincode** [comment]
я не про этом, я знаю, что в гите не хранят скомпилированные файлы и тп, но я не понимаю смысловую нагрузку этого файла

**Comment by aiboy** [comment]
@splincode папка bin нужна для файлов которы являются входной точкой для CLI интерфайса модуля

http://blog.npmjs.org/post/118810260230/building-a-simple-command-line-tool-with-npm

это стандартная практика создавать bin файл и в нем фактически редиректить на файл с кодом (просто require index.js)

иногда он бывает пожирнее но он все равно всегда есть https://github.com/iandotkelly/aws-cli/blob/master/bin/aws.js

**Comment by splincode** [comment]
Да, опыта не было в этом, теперь буду знать, спасибо!
